coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  nodejs:
    paths:
      - nodejs/
  rust:
    paths:
      - mdi-core/
  swift:
    paths:
      - swift/

ignore:
  - nodejs/**/dist/
  - nodejs/docs/
  - python/
